### PR TITLE
Added a postprocessor option so other markup languages can be used

### PR DESCRIPTION
**Pull request by diego-treitos**
I added some bloat so I can post process the drafts and therefore be able to use other markup languages than html.

### CODE REVIEW

**Comment by diego-treitos** [comment]
I am sorry, I only wanted to merge the postprocessor option but I after checking the PR I see that I created a lot of noise with other commits that probably @LukeSmithxyz is not interested in. I am closing the PR.
Feel free to cherry pick the postrpocessor commit.

**Comment by terminalforlife** [comment]
I don't think you did anything wrong. Personally, I had no idea this PR existed while I was working on his code. I did it because I saw code which could be improved, and I like shell programming.

**Comment by diego-treitos** [comment]
Hehe, I know. It is just that I thought the PR would be based in the commit where I requested the PR, not in the whole branch. So I kept working in the branch to change the script for my needs without knowing that it was affecting the PR.

I love shell coding too :) Cheers !

**Comment by terminalforlife** [comment]
Oh Lol. Yeah, next time, to avoid that happening, you are probably better off creating a branch for that purpose. A common name I see has 'patch' in it. I might check out your stuff too. :) Have a good day.

**Pull request closed without merging**
